name: Release Build & Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
          channel: 'stable'

      - run: flutter pub get

      - name: Create .env for build
        run: |
          echo "SUPABASE_URL=https://brkylvdfffjmfaiebgcf.supabase.co" > .env
          echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJya3lsdmRmZmZqbWZhaWViZ2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0MzM3MDUsImV4cCI6MjA5NTAwOTcwNX0.UTXReSb48dVksnDuTE1YAMEaNlrAJTfT8tWRmTMjTy8" >> .env

      - run: flutter build apk --release

      - name: Rename APK
        run: cp build/app/outputs/flutter-apk/app-release.apk Rynix_E-Ticketing_Helpdesk.apk

      - name: Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: Rynix_E-Ticketing_Helpdesk.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
